// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webproject.Models;

namespace webproject.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220517153649_ver")]
    partial class ver
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webproject.Models.YaziTuru", b =>
                {
                    b.Property<int>("Yazıid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Yazıid");

                    b.ToTable("YaziTurus");
                });

            modelBuilder.Entity("webproject.Models.Yazı", b =>
                {
                    b.Property<int>("Yid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("YaziAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yazıid")
                        .HasColumnType("int");

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resmi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Yid");

                    b.HasIndex("Yazıid");

                    b.ToTable("Yazis");
                });

            modelBuilder.Entity("webproject.Models.Yazı", b =>
                {
                    b.HasOne("webproject.Models.YaziTuru", "YazıTuru")
                        .WithMany()
                        .HasForeignKey("Yazıid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YazıTuru");
                });
#pragma warning restore 612, 618
        }
    }
}
